### ISSUE TITLE
broken in latest web-browsers

### ISSUE THREAD

**Issue by opcodewriter** [websemantics/Hotdraw.js#1]
`http://oeasvg.com/bower_components/Hotdraw.js/index.html` is broken in latest Chrome

> Uncaught TypeError: this.getNode(...).getTransformToElement is not a function

A polyfill is required 

```
SVGElement.prototype.getTransformToElement = SVGElement.prototype.getTransformToElement || function(elem) {
    return elem.getScreenCTM().inverse().multiply(this.getScreenCTM());
};
```

https://github.com/cpettitt/dagre-d3/issues/202

**Comment by websemantics** [comment]
Thanks @opcodewriter for reporting the issue and the suggested solution, .. it should work now.

**Comment by opcodewriter** [comment]
wow, nice, thanks!

**Comment by opcodewriter** [comment]
You might wan to checkout the console in Chrome, it still gives errors when playing around

>         // Ignore keydown event if typing in an input box
>         if ((document.activeElement.nodeName === 'INPUT'
>
